//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWPatcher.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ko {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ko() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SWPatcher.Resources.ko", typeof(ko).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 게임 경로.
        /// </summary>
        internal static string box_game_dir {
            get {
                return ResourceManager.GetString("box_game_dir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 소울워커 ID.
        /// </summary>
        internal static string box_id {
            get {
                return ResourceManager.GetString("box_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 언어.
        /// </summary>
        internal static string box_language {
            get {
                return ResourceManager.GetString("box_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 유니코드 기능 서포트 (필요).
        /// </summary>
        internal static string box_patch_exe {
            get {
                return ResourceManager.GetString("box_patch_exe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 패쳐 경로.
        /// </summary>
        internal static string box_patcher_dir {
            get {
                return ResourceManager.GetString("box_patcher_dir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 소울워커 패스워드.
        /// </summary>
        internal static string box_pw {
            get {
                return ResourceManager.GetString("box_pw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 인터페이스 스타일.
        /// </summary>
        internal static string box_ui_style {
            get {
                return ResourceManager.GetString("box_ui_style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 웹사이트에서 부터 로그인하는게 피곤한가요?.
        /// </summary>
        internal static string box_want_login {
            get {
                return ResourceManager.GetString("box_want_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 적용.
        /// </summary>
        internal static string button_apply {
            get {
                return ResourceManager.GetString("button_apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 취소.
        /// </summary>
        internal static string button_cancel {
            get {
                return ResourceManager.GetString("button_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 취소중....
        /// </summary>
        internal static string button_cancelling {
            get {
                return ResourceManager.GetString("button_cancelling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 변경.
        /// </summary>
        internal static string button_change {
            get {
                return ResourceManager.GetString("button_change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 번역 다운로드.
        /// </summary>
        internal static string button_download_translation {
            get {
                return ResourceManager.GetString("button_download_translation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 닫기.
        /// </summary>
        internal static string button_exit {
            get {
                return ResourceManager.GetString("button_exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string button_ok {
            get {
                return ResourceManager.GetString("button_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready To Play!.
        /// </summary>
        internal static string button_play {
            get {
                return ResourceManager.GetString("button_play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 일본어로 진행.
        /// </summary>
        internal static string button_play_raw {
            get {
                return ResourceManager.GetString("button_play_raw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 네, 리스크를 감수하고 패치하겠습니다.
        /// </summary>
        internal static string check_patch_exe {
            get {
                return ResourceManager.GetString("check_patch_exe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 패쳐를 통해 로그인.
        /// </summary>
        internal static string check_want_login {
            get {
                return ResourceManager.GetString("check_want_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 소울워커 게임 클라이언트 폴더를 선택해주십시오..
        /// </summary>
        internal static string dialog_folder_change_game_dir {
            get {
                return ResourceManager.GetString("dialog_folder_change_game_dir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 새로운 패쳐 폴더를 지정해주십시오..
        /// </summary>
        internal static string dialog_folder_change_patcher_dir {
            get {
                return ResourceManager.GetString("dialog_folder_change_patcher_dir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 이미 이 언어의 최신 번역이 업데이트되있습니다!.
        /// </summary>
        internal static string exception_already_latest_translation {
            get {
                return ResourceManager.GetString("exception_already_latest_translation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} 는 현재 작업중이라 닫을수 없습니다..
        /// </summary>
        internal static string exception_cannot_close {
            get {
                return ResourceManager.GetString("exception_cannot_close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 파일 경로가 존재하지 않습니다. &quot;{0}&quot; 가 없습니다. 파일 복구 불가능, 삭제합니다..
        /// </summary>
        internal static string exception_cannot_restore_file {
            get {
                return ResourceManager.GetString("exception_cannot_restore_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 로그인 시도 횟수를 초과하였습니다. 한게임 JP 사이트에 로그인을해서 캡챠를 입력하셔야합니다..
        /// </summary>
        internal static string exception_captcha_validation {
            get {
                return ResourceManager.GetString("exception_captcha_validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 지정된 폴더가 소울워커 게임 클라이언트 폴더가 아닙니다..
        /// </summary>
        internal static string exception_folder_not_game_folder {
            get {
                return ResourceManager.GetString("exception_folder_not_game_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 프로그램이 게임 파일내에 있습니다.
        ///게임 클라이언트에 오류및 오염을 일으킬수도 있습니다.
        ///다른 경로로 패쳐를 이동하거나 리스크름 감수하고 진행해주세요..
        /// </summary>
        internal static string exception_folder_same_path_game {
            get {
                return ResourceManager.GetString("exception_folder_same_path_game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}가  이미 실행중이므로 진행이 불가능합니다..
        /// </summary>
        internal static string exception_game_already_open {
            get {
                return ResourceManager.GetString("exception_game_already_open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 소울워커 프로그램이 감지되지 않습니다..
        /// </summary>
        internal static string exception_game_install_not_found {
            get {
                return ResourceManager.GetString("exception_game_install_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 소울워커는 현재 점검중입니다..
        /// </summary>
        internal static string exception_game_maintenance {
            get {
                return ResourceManager.GetString("exception_game_maintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 소울워커 혹은 한게임JP 서버가 연결을 차단하였습니다. (점검 스케줄을 체크해주세요).
        /// </summary>
        internal static string exception_hangame_refused_connection {
            get {
                return ResourceManager.GetString("exception_hangame_refused_connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID 혹은 비밀번호가 틀렸습니다..
        /// </summary>
        internal static string exception_incorrect_id_pw {
            get {
                return ResourceManager.GetString("exception_incorrect_id_pw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 로그를 업로드하는데 실패하였습니다..
        /// </summary>
        internal static string exception_log_file_failed {
            get {
                return ResourceManager.GetString("exception_log_file_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 로그 파일이 존재하지 않습니다..
        /// </summary>
        internal static string exception_log_not_exist {
            get {
                return ResourceManager.GetString("exception_log_not_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 다이렉트 로그인이 현재 활성화되있지 않습니다..
        /// </summary>
        internal static string exception_not_login_option {
            get {
                return ResourceManager.GetString("exception_not_login_option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 게임을 플레이하려면 이용약관에 먼저 동의하셔야합니다..
        /// </summary>
        internal static string exception_not_tos {
            get {
                return ResourceManager.GetString("exception_not_tos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 번역 버전을 읽는데 오류가 발생했습니다. 메뉴 -&gt; 강제 패치를 해주십시오..
        /// </summary>
        internal static string exception_read_translation_ini {
            get {
                return ResourceManager.GetString("exception_read_translation_ini", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 인증 실패하였습니다..
        /// </summary>
        internal static string exception_retry_validation_failed {
            get {
                return ResourceManager.GetString("exception_retry_validation_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 오염된 패치 파일 &quot;{0}&quot;.
        /// </summary>
        internal static string exception_rtpatch_corrupt {
            get {
                return ResourceManager.GetString("exception_rtpatch_corrupt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 오염된 파일 &quot;{0}&quot;.
        /// </summary>
        internal static string exception_rtpatch_corrupt_file {
            get {
                return ResourceManager.GetString("exception_rtpatch_corrupt_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 파일이 존재하지 않습니다 &quot;{0}&quot;.
        /// </summary>
        internal static string exception_rtpatch_missing_file {
            get {
                return ResourceManager.GetString("exception_rtpatch_missing_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 경로가 존재하지 않습니다. 게임 경로가 제대로 설정되어있는지 확인해주십시오..
        /// </summary>
        internal static string exception_rtpatch_not_exist_directory {
            get {
                return ResourceManager.GetString("exception_rtpatch_not_exist_directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 파일명을 수정하는데 실패했습니다. 재시도해주세요..
        /// </summary>
        internal static string exception_rtpatch_rename_fail {
            get {
                return ResourceManager.GetString("exception_rtpatch_rename_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 소울워커를 업데이트중 발생미상의 오류가 발생하였습니다. 지금으로써 알려진 고치는 방법은 소울워커를 재인스톨 하는것 뿐입니다. 코드=[{0}]
        ///&quot;{1}&quot; 가 패쳐의 향상을 위해 업로드되었습니다..
        /// </summary>
        internal static string exception_rtpatch_result {
            get {
                return ResourceManager.GetString("exception_rtpatch_result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 인증 실패하였습니다. IP/지정 나라가 차단되있는게 아닐지?.
        /// </summary>
        internal static string exception_validation_failed {
            get {
                return ResourceManager.GetString("exception_validation_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string form_about {
            get {
                return ResourceManager.GetString("form_about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 강제 패치.
        /// </summary>
        internal static string form_force_patch {
            get {
                return ResourceManager.GetString("form_force_patch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - ({1}) 의 새로운 번역.
        /// </summary>
        internal static string form_label_new_translation {
            get {
                return ResourceManager.GetString("form_label_new_translation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 메뉴.
        /// </summary>
        internal static string form_menu {
            get {
                return ResourceManager.GetString("form_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 소워 웹사이트 열기.
        /// </summary>
        internal static string form_open_sw_webpage {
            get {
                return ResourceManager.GetString("form_open_sw_webpage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 새로고침.
        /// </summary>
        internal static string form_refresh {
            get {
                return ResourceManager.GetString("form_refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 설정.
        /// </summary>
        internal static string form_settings {
            get {
                return ResourceManager.GetString("form_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 적용중....
        /// </summary>
        internal static string form_status_apply {
            get {
                return ResourceManager.GetString("form_status_apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 다운로드중....
        /// </summary>
        internal static string form_status_download {
            get {
                return ResourceManager.GetString("form_status_download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string form_status_idle {
            get {
                return ResourceManager.GetString("form_status_idle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 실행중....
        /// </summary>
        internal static string form_status_patch {
            get {
                return ResourceManager.GetString("form_status_patch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .exe 패치중....
        /// </summary>
        internal static string form_status_patch_exe {
            get {
                return ResourceManager.GetString("form_status_patch_exe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 준비중....
        /// </summary>
        internal static string form_status_prepare {
            get {
                return ResourceManager.GetString("form_status_prepare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string form_status_update_client {
            get {
                return ResourceManager.GetString("form_status_update_client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 클라이언트 대기중....
        /// </summary>
        internal static string form_status_wait_client {
            get {
                return ResourceManager.GetString("form_status_wait_client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 클라이언트 중단대기중....
        /// </summary>
        internal static string form_status_wait_close {
            get {
                return ResourceManager.GetString("form_status_wait_close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pastebin으로 로그 업로드.
        /// </summary>
        internal static string form_upload_log {
            get {
                return ResourceManager.GetString("form_upload_log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows 일치.
        /// </summary>
        internal static string match_windows {
            get {
                return ResourceManager.GetString("match_windows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 번역파일이 최신이 아닌것을 확인, 강제 패치를 강행합니다..
        /// </summary>
        internal static string notice_outdated_translation {
            get {
                return ResourceManager.GetString("notice_outdated_translation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 몇몇 변경은 애플리케이션을 재시작한 이후에 적용됩니다..
        /// </summary>
        internal static string notice_pending_restart {
            get {
                return ResourceManager.GetString("notice_pending_restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 더블클릭으로 복구....
        /// </summary>
        internal static string notify_balloon_text {
            get {
                return ResourceManager.GetString("notify_balloon_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 패쳐는 이제 여기에 숨겨집니다..
        /// </summary>
        internal static string notify_balloon_title {
            get {
                return ResourceManager.GetString("notify_balloon_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 소울워커 패쳐.
        /// </summary>
        internal static string notify_text {
            get {
                return ResourceManager.GetString("notify_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 소울워커 패쳐는 최신의 번역 파일들을 소울워커 클라이언트에 오류 없이 깨끗하게 업데이트 하기 위해 만들어진 프로그램 입니다.
        ///또한, SWHQ 번역팀(한국번역은 소울워커 카페 번역팀)에 의해 번역이 된 최신번역 파일들을 손쉽게 다운로드하고 적용시킬수 있습니다..
        /// </summary>
        internal static string patcher_description {
            get {
                return ResourceManager.GetString("patcher_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 백엄 파일 확인. 클라이언트에 이 파일을을 복구시키겠습니까?
        ///현재 클라이언트에 있는 파일들은 {0} 번역으로 교체됩니다.
        ///아니요를 선택하시면 백업 파일들이 삭제됩니다..
        /// </summary>
        internal static string question_backup_files_found {
            get {
                return ResourceManager.GetString("question_backup_files_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 프로그램이 게임 파일내에 있습니다.
        ///게임 클라이언트에 오류및 오염을 일으킬수도 있습니다.
        ///정말 이 폴더로 지정하겠습니까?.
        /// </summary>
        internal static string question_folder_same_path_game {
            get {
                return ResourceManager.GetString("question_folder_same_path_game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full.
        /// </summary>
        internal static string radio_full {
            get {
                return ResourceManager.GetString("radio_full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimal.
        /// </summary>
        internal static string radio_min {
            get {
                return ResourceManager.GetString("radio_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 로그파일이 &quot;{0}&quot; 로 업로드되었습니다.
        ///링크가 클립보드로 복사되었습니다..
        /// </summary>
        internal static string success_log_file_upload {
            get {
                return ResourceManager.GetString("success_log_file_upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 계정.
        /// </summary>
        internal static string tab_credentials {
            get {
                return ResourceManager.GetString("tab_credentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 소울워커.
        /// </summary>
        internal static string tab_game {
            get {
                return ResourceManager.GetString("tab_game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 패쳐.
        /// </summary>
        internal static string tab_patcher {
            get {
                return ResourceManager.GetString("tab_patcher", resourceCulture);
            }
        }
    }
}
