//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWPatcher.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class vi {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal vi() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SWPatcher.Resources.vi", typeof(vi).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đường dẫn của game.
        /// </summary>
        internal static string box_game_dir {
            get {
                return ResourceManager.GetString("box_game_dir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thay đổi tùy chỉnh trong game.
        /// </summary>
        internal static string box_game_options {
            get {
                return ResourceManager.GetString("box_game_options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soulworker ID.
        /// </summary>
        internal static string box_id {
            get {
                return ResourceManager.GetString("box_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngôn ngữ.
        /// </summary>
        internal static string box_language {
            get {
                return ResourceManager.GetString("box_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉnh sửa .exe để hỗ trợ ký tự Unicode.
        /// </summary>
        internal static string box_patch_exe {
            get {
                return ResourceManager.GetString("box_patch_exe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đường dẫn Patcher.
        /// </summary>
        internal static string box_patcher_dir {
            get {
                return ResourceManager.GetString("box_patcher_dir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soulworker Password.
        /// </summary>
        internal static string box_pw {
            get {
                return ResourceManager.GetString("box_pw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngán ngẩm phải đăng nhập từ website?.
        /// </summary>
        internal static string box_want_login {
            get {
                return ResourceManager.GetString("box_want_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Áp dụng.
        /// </summary>
        internal static string button_apply {
            get {
                return ResourceManager.GetString("button_apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hủy bỏ.
        /// </summary>
        internal static string button_cancel {
            get {
                return ResourceManager.GetString("button_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang hủy bỏ....
        /// </summary>
        internal static string button_cancelling {
            get {
                return ResourceManager.GetString("button_cancelling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thay đổi.
        /// </summary>
        internal static string button_change {
            get {
                return ResourceManager.GetString("button_change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tải bản dịch.
        /// </summary>
        internal static string button_download_translation {
            get {
                return ResourceManager.GetString("button_download_translation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thoát.
        /// </summary>
        internal static string button_exit {
            get {
                return ResourceManager.GetString("button_exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tùy chỉnh trò chơi.
        /// </summary>
        internal static string button_game_options {
            get {
                return ResourceManager.GetString("button_game_options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string button_ok {
            get {
                return ResourceManager.GetString("button_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready To Play!.
        /// </summary>
        internal static string button_play {
            get {
                return ResourceManager.GetString("button_play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bắt đầu trò chơi mà không dùng Patch.
        /// </summary>
        internal static string button_play_raw {
            get {
                return ResourceManager.GetString("button_play_raw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tôi đồng ý với rủi ro và đồng ý chỉnh sửa..
        /// </summary>
        internal static string check_patch_exe {
            get {
                return ResourceManager.GetString("check_patch_exe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập bằng Patcher.
        /// </summary>
        internal static string check_want_login {
            get {
                return ResourceManager.GetString("check_want_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn đến thư mục game..
        /// </summary>
        internal static string dialog_folder_change_game_dir {
            get {
                return ResourceManager.GetString("dialog_folder_change_game_dir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn đến thư mục mà Patcher làm việc..
        /// </summary>
        internal static string dialog_folder_change_patcher_dir {
            get {
                return ResourceManager.GetString("dialog_folder_change_patcher_dir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể patch tập tin .exe vì lý do phương thức &quot;{0}&quot; chưa được cập nhật cho client hiện tại. Patch cho client đã bị vô hiệu hóa. Client vẫn sẽ được cập nhật, ngoại trừ việc một vài đoạn chữ sẽ không hiện. Xin vui lòng thử lại sau khi &quot;{0}&quot; đã được hoàn thiện..
        /// </summary>
        internal static string error_exe_patch_fail {
            get {
                return ResourceManager.GetString("error_exe_patch_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn đã có phiên bản mới nhất ({0} JST) của bản dịch này!.
        /// </summary>
        internal static string exception_already_latest_translation {
            get {
                return ResourceManager.GetString("exception_already_latest_translation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} đang bận và không thể thoát..
        /// </summary>
        internal static string exception_cannot_close {
            get {
                return ResourceManager.GetString("exception_cannot_close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thư mục bao gồm tập tin &quot;{0}&quot; không tồn tại. Không thể khôi phục, thư mục sẽ bị xóa..
        /// </summary>
        internal static string exception_cannot_restore_file {
            get {
                return ResourceManager.GetString("exception_cannot_restore_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập thất bại quá nhiều. Xin vui lòng đăng nhập và hoàn tất captcha tại trang chủ của Hangame.
        /// </summary>
        internal static string exception_captcha_validation {
            get {
                return ResourceManager.GetString("exception_captcha_validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể truy cập vào thư mục &quot;{0}&quot;..
        /// </summary>
        internal static string exception_directory_rights {
            get {
                return ResourceManager.GetString("exception_directory_rights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID không được để trống, xin vui lòng nhập ID hoặc bỏ chọn &quot;Đăng nhập bằng Patcher&quot;.
        /// </summary>
        internal static string exception_empty_id {
            get {
                return ResourceManager.GetString("exception_empty_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password không được để trống, xin vui lòng nhập Password hoặc bỏ chọn &quot;Đăng nhập bằng Patcher&quot;.
        /// </summary>
        internal static string exception_empty_pw {
            get {
                return ResourceManager.GetString("exception_empty_pw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected folder is not a Soulworker game client folder..
        /// </summary>
        internal static string exception_folder_not_game_folder {
            get {
                return ResourceManager.GetString("exception_folder_not_game_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thư mục hoạt động của Patcher đang ở trong thư mục của game.
        ///Điều này có thể gây ra xung đột hoặc hỏng hóc tệp tin của game.
        ///Xin vui lòng di chuyển thư mục đến địa điểm khác hoặc chấp nhận rủi ro và tiếp tục dùng..
        /// </summary>
        internal static string exception_folder_same_path_game {
            get {
                return ResourceManager.GetString("exception_folder_same_path_game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể tiếp tục vì {0} đang chạy..
        /// </summary>
        internal static string exception_game_already_open {
            get {
                return ResourceManager.GetString("exception_game_already_open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy Soulworker..
        /// </summary>
        internal static string exception_game_install_not_found {
            get {
                return ResourceManager.GetString("exception_game_install_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Máy chủ Soulworker đang trong bảo trì..
        /// </summary>
        internal static string exception_game_maintenance {
            get {
                return ResourceManager.GetString("exception_game_maintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Máy chủ SoulWorker từ chối kết nối (bảo trì ???).
        /// </summary>
        internal static string exception_hangame_refused_connection {
            get {
                return ResourceManager.GetString("exception_hangame_refused_connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sai ID hoặc mật khẩu..
        /// </summary>
        internal static string exception_incorrect_id_pw {
            get {
                return ResourceManager.GetString("exception_incorrect_id_pw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng tệp log thất bại..
        /// </summary>
        internal static string exception_log_file_failed {
            get {
                return ResourceManager.GetString("exception_log_file_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tệp Log không tồn tại..
        /// </summary>
        internal static string exception_log_not_exist {
            get {
                return ResourceManager.GetString("exception_log_not_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập bằng Patcher không được sử dụng..
        /// </summary>
        internal static string exception_not_login_option {
            get {
                return ResourceManager.GetString("exception_not_login_option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Để tham gia trò chơi, bạn phải đồng ý Điều khoản dịch vụ..
        /// </summary>
        internal static string exception_not_tos {
            get {
                return ResourceManager.GetString("exception_not_tos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi khi đọc phiên bản của bản dịch, xin vui lòng nhấn thử Menu -&gt; Làm lại Patch mới.
        /// </summary>
        internal static string exception_read_translation_ini {
            get {
                return ResourceManager.GetString("exception_read_translation_ini", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kiểm tra thất bại..
        /// </summary>
        internal static string exception_retry_validation_failed {
            get {
                return ResourceManager.GetString("exception_retry_validation_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật tập tin tất bại vì thiếu quyền truy cập hoặc tập tin đang được sử dụng. Xin vui lòng thử lại..
        /// </summary>
        internal static string exception_rtpatch_administrator_required {
            get {
                return ResourceManager.GetString("exception_rtpatch_administrator_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tập tin patch &quot;{0}&quot; đã bị hỏng.
        /// </summary>
        internal static string exception_rtpatch_corrupt {
            get {
                return ResourceManager.GetString("exception_rtpatch_corrupt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tập tin &quot;{0}&quot; đã bị hỏng.
        /// </summary>
        internal static string exception_rtpatch_corrupt_file {
            get {
                return ResourceManager.GetString("exception_rtpatch_corrupt_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật thất bại vì thiếu không gian trống trên ổ đĩa..
        /// </summary>
        internal static string exception_rtpatch_insufficient_storage {
            get {
                return ResourceManager.GetString("exception_rtpatch_insufficient_storage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tập tin &quot;{0}&quot; không tồn tại.
        /// </summary>
        internal static string exception_rtpatch_missing_file {
            get {
                return ResourceManager.GetString("exception_rtpatch_missing_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thư mục không tồn tại, xin vui lòng kiểm tra lại đường dẫn.
        /// </summary>
        internal static string exception_rtpatch_not_exist_directory {
            get {
                return ResourceManager.GetString("exception_rtpatch_not_exist_directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mở tập tin patch thất bại. Xin vui lòng thử lại..
        /// </summary>
        internal static string exception_rtpatch_open_patch_file_fail {
            get {
                return ResourceManager.GetString("exception_rtpatch_open_patch_file_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đọc tập tin patch thất bại. Vui lòng thử lại sau..
        /// </summary>
        internal static string exception_rtpatch_read_patch_file_fail {
            get {
                return ResourceManager.GetString("exception_rtpatch_read_patch_file_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đổi tên tập tin thất bại, xin hãy thử lại.
        /// </summary>
        internal static string exception_rtpatch_rename_fail {
            get {
                return ResourceManager.GetString("exception_rtpatch_rename_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra trong lúc cập nhật SoulWorker, cách tốt nhất là cài đặt lại trò chơi. Code=[{0}]
        ///&quot;{1}&quot; đã được đăng lên để cải thiện patcher..
        /// </summary>
        internal static string exception_rtpatch_result {
            get {
                return ResourceManager.GetString("exception_rtpatch_result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đặt mốc thời gian cho tập tin thất bại. Xin vui lòng thử lại..
        /// </summary>
        internal static string exception_rtpatch_time_date_fail {
            get {
                return ResourceManager.GetString("exception_rtpatch_time_date_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kiểm tra thất bại. Bạn có chắc rằng bạn không bị chặn?.
        /// </summary>
        internal static string exception_validation_failed {
            get {
                return ResourceManager.GetString("exception_validation_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin.
        /// </summary>
        internal static string form_about {
            get {
                return ResourceManager.GetString("form_about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Làm lại Patch mới.
        /// </summary>
        internal static string form_force_patch {
            get {
                return ResourceManager.GetString("form_force_patch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có bản dịch mới cho {0} - ({1}).
        /// </summary>
        internal static string form_label_new_translation {
            get {
                return ResourceManager.GetString("form_label_new_translation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        internal static string form_menu {
            get {
                return ResourceManager.GetString("form_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mở trang chủ SW.
        /// </summary>
        internal static string form_open_sw_webpage {
            get {
                return ResourceManager.GetString("form_open_sw_webpage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string form_refresh {
            get {
                return ResourceManager.GetString("form_refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cài đặt.
        /// </summary>
        internal static string form_settings {
            get {
                return ResourceManager.GetString("form_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang áp dụng....
        /// </summary>
        internal static string form_status_apply {
            get {
                return ResourceManager.GetString("form_status_apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang tải....
        /// </summary>
        internal static string form_status_download {
            get {
                return ResourceManager.GetString("form_status_download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string form_status_idle {
            get {
                return ResourceManager.GetString("form_status_idle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang làm việc....
        /// </summary>
        internal static string form_status_patch {
            get {
                return ResourceManager.GetString("form_status_patch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patching .exe....
        /// </summary>
        internal static string form_status_patch_exe {
            get {
                return ResourceManager.GetString("form_status_patch_exe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.....
        /// </summary>
        internal static string form_status_patch_load {
            get {
                return ResourceManager.GetString("form_status_patch_load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang cập nhật.....
        /// </summary>
        internal static string form_status_patch_patch {
            get {
                return ResourceManager.GetString("form_status_patch_patch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang lưu lại.....
        /// </summary>
        internal static string form_status_patch_save {
            get {
                return ResourceManager.GetString("form_status_patch_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang chuẩn bị....
        /// </summary>
        internal static string form_status_prepare {
            get {
                return ResourceManager.GetString("form_status_prepare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string form_status_update_client {
            get {
                return ResourceManager.GetString("form_status_update_client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang chờ khởi động game....
        /// </summary>
        internal static string form_status_wait_client {
            get {
                return ResourceManager.GetString("form_status_wait_client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang chời thoát game....
        /// </summary>
        internal static string form_status_wait_close {
            get {
                return ResourceManager.GetString("form_status_wait_close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng tệp Log lên Pastebin.
        /// </summary>
        internal static string form_upload_log {
            get {
                return ResourceManager.GetString("form_upload_log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tự động.
        /// </summary>
        internal static string match_windows {
            get {
                return ResourceManager.GetString("match_windows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bản dịch lỗi thời, tiến hành làm lại Patch mới..
        /// </summary>
        internal static string notice_outdated_translation {
            get {
                return ResourceManager.GetString("notice_outdated_translation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Một vài thay đổi sẽ được áp dụng sau khi khởi động lại chương trình..
        /// </summary>
        internal static string notice_pending_restart {
            get {
                return ResourceManager.GetString("notice_pending_restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double click để hiện....
        /// </summary>
        internal static string notify_balloon_text {
            get {
                return ResourceManager.GetString("notify_balloon_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patcher ẩn ở đây.
        /// </summary>
        internal static string notify_balloon_title {
            get {
                return ResourceManager.GetString("notify_balloon_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soulworker Patcher.
        /// </summary>
        internal static string notify_text {
            get {
                return ResourceManager.GetString("notify_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This program comes with ABSOLUTELY NO WARRANTY
        ///This is free software, and you are welcome to redistribute it under certain conditions.
        ///
        ///Soulworker Patcher được làm ra là để áp dụng các bản dịch vào game mà không gây ra nhiều rủi ro hỏng tệp của game.
        ///Nguồn dịch được tải từ nhóm dịch ở SWHQ..
        /// </summary>
        internal static string patcher_description {
            get {
                return ResourceManager.GetString("patcher_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm thấy Backup. Bạn có muốn khôi phục backup về thư mục game không?
        ///Tệp đang tồn tại ở thư mục game sẽ bị hoán đổi với bản dịch {0}.
        ///Chọn No sẽ tiến hành xóa backup..
        /// </summary>
        internal static string question_backup_files_found {
            get {
                return ResourceManager.GetString("question_backup_files_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Điểm đến đang ở trong thư mục của game.
        ///Điều này có thể gây ra xung đột hoặc hỏng hóc tệp tin của game.
        ///Bạn có chắc rằng bạn muốn chọn thư mục này?.
        /// </summary>
        internal static string question_folder_same_path_game {
            get {
                return ResourceManager.GetString("question_folder_same_path_game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tệp Log đã được đăng &quot;{0}&quot;
        ///Đường link đã được copy vào clipboard..
        /// </summary>
        internal static string success_log_file_upload {
            get {
                return ResourceManager.GetString("success_log_file_upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin đăng nhập.
        /// </summary>
        internal static string tab_credentials {
            get {
                return ResourceManager.GetString("tab_credentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soulworker.
        /// </summary>
        internal static string tab_game {
            get {
                return ResourceManager.GetString("tab_game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patcher.
        /// </summary>
        internal static string tab_patcher {
            get {
                return ResourceManager.GetString("tab_patcher", resourceCulture);
            }
        }
    }
}
