//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWPatcher.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class zh {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal zh() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SWPatcher.Resources.zh", typeof(zh).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 游戏位置 的本地化字符串。
        /// </summary>
        internal static string box_game_dir {
            get {
                return ResourceManager.GetString("box_game_dir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更改游戏内选项 的本地化字符串。
        /// </summary>
        internal static string box_game_options {
            get {
                return ResourceManager.GetString("box_game_options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Soulworker ID 的本地化字符串。
        /// </summary>
        internal static string box_id {
            get {
                return ResourceManager.GetString("box_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 语言 的本地化字符串。
        /// </summary>
        internal static string box_language {
            get {
                return ResourceManager.GetString("box_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改 .exe 文件以支持其它 unicode 语言 的本地化字符串。
        /// </summary>
        internal static string box_patch_exe {
            get {
                return ResourceManager.GetString("box_patch_exe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改器位置 的本地化字符串。
        /// </summary>
        internal static string box_patcher_dir {
            get {
                return ResourceManager.GetString("box_patcher_dir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Soulworker 密码 的本地化字符串。
        /// </summary>
        internal static string box_pw {
            get {
                return ResourceManager.GetString("box_pw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不想从网页登陆了？ 的本地化字符串。
        /// </summary>
        internal static string box_want_login {
            get {
                return ResourceManager.GetString("box_want_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 应用 的本地化字符串。
        /// </summary>
        internal static string button_apply {
            get {
                return ResourceManager.GetString("button_apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        internal static string button_cancel {
            get {
                return ResourceManager.GetString("button_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在取消... 的本地化字符串。
        /// </summary>
        internal static string button_cancelling {
            get {
                return ResourceManager.GetString("button_cancelling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更改 的本地化字符串。
        /// </summary>
        internal static string button_change {
            get {
                return ResourceManager.GetString("button_change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下载翻译 的本地化字符串。
        /// </summary>
        internal static string button_download_translation {
            get {
                return ResourceManager.GetString("button_download_translation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退出 的本地化字符串。
        /// </summary>
        internal static string button_exit {
            get {
                return ResourceManager.GetString("button_exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 游戏选项 的本地化字符串。
        /// </summary>
        internal static string button_game_options {
            get {
                return ResourceManager.GetString("button_game_options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OK 的本地化字符串。
        /// </summary>
        internal static string button_ok {
            get {
                return ResourceManager.GetString("button_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开 的本地化字符串。
        /// </summary>
        internal static string button_open {
            get {
                return ResourceManager.GetString("button_open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 准备开玩！ 的本地化字符串。
        /// </summary>
        internal static string button_play {
            get {
                return ResourceManager.GetString("button_play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 直接启动原始游戏 的本地化字符串。
        /// </summary>
        internal static string button_play_raw {
            get {
                return ResourceManager.GetString("button_play_raw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是，我了解风险，决定修改 的本地化字符串。
        /// </summary>
        internal static string check_patch_exe {
            get {
                return ResourceManager.GetString("check_patch_exe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用修改器登陆 的本地化字符串。
        /// </summary>
        internal static string check_want_login {
            get {
                return ResourceManager.GetString("check_want_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择 Soulworker 客户端文件夹。 的本地化字符串。
        /// </summary>
        internal static string dialog_folder_change_game_dir {
            get {
                return ResourceManager.GetString("dialog_folder_change_game_dir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择新的修改器数据文件夹。 的本地化字符串。
        /// </summary>
        internal static string dialog_folder_change_patcher_dir {
            get {
                return ResourceManager.GetString("dialog_folder_change_patcher_dir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 .exe 未应用修改，因为在最近一次更新后，客户端文件 &quot;{0}&quot; 未更新。客户端修改已禁用。游戏仍然可以运行，只不过一些文本无法显示。请在更新 &quot;{0}&quot; 后重试。 的本地化字符串。
        /// </summary>
        internal static string error_exe_patch_fail {
            get {
                return ResourceManager.GetString("error_exe_patch_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您的 Soulworker 区服不支持 .exe 修改。客户端修改已禁用。游戏仍然可以运行，只不过一些文本无法显示。 的本地化字符串。
        /// </summary>
        internal static string error_exe_region_not_supported {
            get {
                return ResourceManager.GetString("error_exe_region_not_supported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您的 Soulworker 账号未验证。请在网页上认证账号。 的本地化字符串。
        /// </summary>
        internal static string exception_account_not_validated {
            get {
                return ResourceManager.GetString("exception_account_not_validated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 这个账号正在等待删除。如果你想取消，请与客服练习。 的本地化字符串。
        /// </summary>
        internal static string exception_account_to_be_deleted {
            get {
                return ResourceManager.GetString("exception_account_to_be_deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您已有此语言的最新（日本时间 {0}）翻译！ 的本地化字符串。
        /// </summary>
        internal static string exception_already_latest_translation {
            get {
                return ResourceManager.GetString("exception_already_latest_translation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 正忙，无法关闭。 的本地化字符串。
        /// </summary>
        internal static string exception_cannot_close {
            get {
                return ResourceManager.GetString("exception_cannot_close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 包含文件 {0} 的目录不存在。无法还原此文件夹，它将被删除。 的本地化字符串。
        /// </summary>
        internal static string exception_cannot_restore_file {
            get {
                return ResourceManager.GetString("exception_cannot_restore_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法使用修改器登陆，因为登陆需要人机验证。 的本地化字符串。
        /// </summary>
        internal static string exception_captcha_required {
            get {
                return ResourceManager.GetString("exception_captcha_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登陆失败过多。您必须登陆 Hange 网站完成人机验证。 的本地化字符串。
        /// </summary>
        internal static string exception_captcha_validation {
            get {
                return ResourceManager.GetString("exception_captcha_validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 游戏目录不存在 &quot;{0}&quot;。 的本地化字符串。
        /// </summary>
        internal static string exception_directory_not_exist {
            get {
                return ResourceManager.GetString("exception_directory_not_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法为游戏文件夹 &quot;{0}&quot; 设置正确权限。 的本地化字符串。
        /// </summary>
        internal static string exception_directory_rights {
            get {
                return ResourceManager.GetString("exception_directory_rights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ID不能为空，请设置您的 Soulworker ID 或取消选择使用修改器登陆。 的本地化字符串。
        /// </summary>
        internal static string exception_empty_id {
            get {
                return ResourceManager.GetString("exception_empty_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码不能为空，请设置您的 Soulworker 密码或取消选择使用修改器登陆。 的本地化字符串。
        /// </summary>
        internal static string exception_empty_pw {
            get {
                return ResourceManager.GetString("exception_empty_pw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选中的文件夹不是 SoulWorker 游戏文件夹。 的本地化字符串。
        /// </summary>
        internal static string exception_folder_not_game_folder {
            get {
                return ResourceManager.GetString("exception_folder_not_game_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改器位于游戏同一文件夹或子文件夹下。
        ///这可能使游戏客户端故障或造成数据冲突。
        ///请移动修改器到其他位置，或无视警告继续，一切后果自负。 的本地化字符串。
        /// </summary>
        internal static string exception_folder_same_path_game {
            get {
                return ResourceManager.GetString("exception_folder_same_path_game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登陆时遇到错误，请按照网站说明操作。 的本地化字符串。
        /// </summary>
        internal static string exception_follow_instruction_webpage {
            get {
                return ResourceManager.GetString("exception_follow_instruction_webpage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法继续，因为 {0} 已在运行。 的本地化字符串。
        /// </summary>
        internal static string exception_game_already_open {
            get {
                return ResourceManager.GetString("exception_game_already_open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未找到 Soulworker {0} 安装。 的本地化字符串。
        /// </summary>
        internal static string exception_game_install_not_found {
            get {
                return ResourceManager.GetString("exception_game_install_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Soulworker 正在维护。 的本地化字符串。
        /// </summary>
        internal static string exception_game_maintenance {
            get {
                return ResourceManager.GetString("exception_game_maintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Soulworker 没有更新至最新版本。请在更新后重试。 的本地化字符串。
        /// </summary>
        internal static string exception_game_not_latest {
            get {
                return ResourceManager.GetString("exception_game_not_latest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Soulworker 维护 {0}
        ///{1}
        ///维护结束于 {2}。
        ///清单:
        ///{3} 的本地化字符串。
        /// </summary>
        internal static string exception_game_stove_maintenance {
            get {
                return ResourceManager.GetString("exception_game_stove_maintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 读取 {0} 失败。 的本地化字符串。
        /// </summary>
        internal static string exception_generic_read_error {
            get {
                return ResourceManager.GetString("exception_generic_read_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ID 或密码错误。 的本地化字符串。
        /// </summary>
        internal static string exception_incorrect_id_pw {
            get {
                return ResourceManager.GetString("exception_incorrect_id_pw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上传日志失败。 的本地化字符串。
        /// </summary>
        internal static string exception_log_file_failed {
            get {
                return ResourceManager.GetString("exception_log_file_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日志文件不存在。 的本地化字符串。
        /// </summary>
        internal static string exception_log_not_exist {
            get {
                return ResourceManager.GetString("exception_log_not_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您的 Soulworker 区服不支持直接登录。登陆选项已禁用。 的本地化字符串。
        /// </summary>
        internal static string exception_login_option_not_supported {
            get {
                return ResourceManager.GetString("exception_login_option_not_supported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 直接登录未启用。 的本地化字符串。
        /// </summary>
        internal static string exception_not_login_option {
            get {
                return ResourceManager.GetString("exception_not_login_option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 想要继续，您需要接受服务条款。 的本地化字符串。
        /// </summary>
        internal static string exception_not_tos {
            get {
                return ResourceManager.GetString("exception_not_tos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 读取翻译版本出错，请尝试 菜单 -&gt; 强制修改 的本地化字符串。
        /// </summary>
        internal static string exception_read_translation_ini {
            get {
                return ResourceManager.GetString("exception_read_translation_ini", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 区服 &quot;{0}&quot; 未知。 的本地化字符串。
        /// </summary>
        internal static string exception_region_unknown {
            get {
                return ResourceManager.GetString("exception_region_unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 验证失败。 的本地化字符串。
        /// </summary>
        internal static string exception_retry_validation_failed {
            get {
                return ResourceManager.GetString("exception_retry_validation_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新失败，因为文件需要管理员权限。也许该文件正在使用中？请重试。 的本地化字符串。
        /// </summary>
        internal static string exception_rtpatch_administrator_required {
            get {
                return ResourceManager.GetString("exception_rtpatch_administrator_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 补丁文件 &quot;{0}&quot; 损坏 的本地化字符串。
        /// </summary>
        internal static string exception_rtpatch_corrupt {
            get {
                return ResourceManager.GetString("exception_rtpatch_corrupt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件损坏 &quot;{0}&quot; 的本地化字符串。
        /// </summary>
        internal static string exception_rtpatch_corrupt_file {
            get {
                return ResourceManager.GetString("exception_rtpatch_corrupt_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开补丁文件出错。请重试。 的本地化字符串。
        /// </summary>
        internal static string exception_rtpatch_error_open_patch_file {
            get {
                return ResourceManager.GetString("exception_rtpatch_error_open_patch_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新失败，因为设备存储空间不足。 的本地化字符串。
        /// </summary>
        internal static string exception_rtpatch_insufficient_storage {
            get {
                return ResourceManager.GetString("exception_rtpatch_insufficient_storage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件不存在 &quot;{0}&quot; 的本地化字符串。
        /// </summary>
        internal static string exception_rtpatch_missing_file {
            get {
                return ResourceManager.GetString("exception_rtpatch_missing_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 目录不存在，请检查游戏目录设置是否正确。 的本地化字符串。
        /// </summary>
        internal static string exception_rtpatch_not_exist_directory {
            get {
                return ResourceManager.GetString("exception_rtpatch_not_exist_directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开补丁文件失败。请重试。 的本地化字符串。
        /// </summary>
        internal static string exception_rtpatch_open_patch_file_fail {
            get {
                return ResourceManager.GetString("exception_rtpatch_open_patch_file_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 拂去补丁文件失败。请重试。 的本地化字符串。
        /// </summary>
        internal static string exception_rtpatch_read_patch_file_fail {
            get {
                return ResourceManager.GetString("exception_rtpatch_read_patch_file_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重命名文件失败。请重试。 的本地化字符串。
        /// </summary>
        internal static string exception_rtpatch_rename_fail {
            get {
                return ResourceManager.GetString("exception_rtpatch_rename_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新 Soulworker 时发生未知错误，此视最佳的修复方法是重装 Soulworker。Code=[{0}]
        ///已上传“{1}”，以便将来改进修改器。 的本地化字符串。
        /// </summary>
        internal static string exception_rtpatch_result {
            get {
                return ResourceManager.GetString("exception_rtpatch_result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置文件时间戳失败。请重试。 的本地化字符串。
        /// </summary>
        internal static string exception_rtpatch_time_date_fail {
            get {
                return ResourceManager.GetString("exception_rtpatch_time_date_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服务器拒绝连接。（服务器维护？） 的本地化字符串。
        /// </summary>
        internal static string exception_server_refused_connection {
            get {
                return ResourceManager.GetString("exception_server_refused_connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 验证失败。也许您的 IP 或地区被禁？ 的本地化字符串。
        /// </summary>
        internal static string exception_validation_failed {
            get {
                return ResourceManager.GetString("exception_validation_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关于 的本地化字符串。
        /// </summary>
        internal static string form_about {
            get {
                return ResourceManager.GetString("form_about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 强制修改 的本地化字符串。
        /// </summary>
        internal static string form_force_patch {
            get {
                return ResourceManager.GetString("form_force_patch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 有新翻译 - ({1}) 的本地化字符串。
        /// </summary>
        internal static string form_label_new_translation {
            get {
                return ResourceManager.GetString("form_label_new_translation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 语言： 的本地化字符串。
        /// </summary>
        internal static string form_language_pick {
            get {
                return ResourceManager.GetString("form_language_pick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 菜单 的本地化字符串。
        /// </summary>
        internal static string form_menu {
            get {
                return ResourceManager.GetString("form_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开 SW 网站 的本地化字符串。
        /// </summary>
        internal static string form_open_sw_webpage {
            get {
                return ResourceManager.GetString("form_open_sw_webpage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 刷新 的本地化字符串。
        /// </summary>
        internal static string form_refresh {
            get {
                return ResourceManager.GetString("form_refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Japan Gamecom 的本地化字符串。
        /// </summary>
        internal static string form_region_gjp {
            get {
                return ResourceManager.GetString("form_region_gjp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Global 的本地化字符串。
        /// </summary>
        internal static string form_region_gl {
            get {
                return ResourceManager.GetString("form_region_gl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Japan Hange 的本地化字符串。
        /// </summary>
        internal static string form_region_jp {
            get {
                return ResourceManager.GetString("form_region_jp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Korea 的本地化字符串。
        /// </summary>
        internal static string form_region_kr {
            get {
                return ResourceManager.GetString("form_region_kr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Korea Naver 的本地化字符串。
        /// </summary>
        internal static string form_region_nkr {
            get {
                return ResourceManager.GetString("form_region_nkr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 区服： 的本地化字符串。
        /// </summary>
        internal static string form_region_pick {
            get {
                return ResourceManager.GetString("form_region_pick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置 的本地化字符串。
        /// </summary>
        internal static string form_settings {
            get {
                return ResourceManager.GetString("form_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 应用中... 的本地化字符串。
        /// </summary>
        internal static string form_status_apply {
            get {
                return ResourceManager.GetString("form_status_apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在下载... 的本地化字符串。
        /// </summary>
        internal static string form_status_download {
            get {
                return ResourceManager.GetString("form_status_download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string form_status_idle {
            get {
                return ResourceManager.GetString("form_status_idle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在运行... 的本地化字符串。
        /// </summary>
        internal static string form_status_patch {
            get {
                return ResourceManager.GetString("form_status_patch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在修改 .exe... 的本地化字符串。
        /// </summary>
        internal static string form_status_patch_exe {
            get {
                return ResourceManager.GetString("form_status_patch_exe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加载中... 的本地化字符串。
        /// </summary>
        internal static string form_status_patch_load {
            get {
                return ResourceManager.GetString("form_status_patch_load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在修改... 的本地化字符串。
        /// </summary>
        internal static string form_status_patch_patch {
            get {
                return ResourceManager.GetString("form_status_patch_patch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在保存... 的本地化字符串。
        /// </summary>
        internal static string form_status_patch_save {
            get {
                return ResourceManager.GetString("form_status_patch_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 准备中... 的本地化字符串。
        /// </summary>
        internal static string form_status_prepare {
            get {
                return ResourceManager.GetString("form_status_prepare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string form_status_update_client {
            get {
                return ResourceManager.GetString("form_status_update_client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 等待客户端... 的本地化字符串。
        /// </summary>
        internal static string form_status_wait_client {
            get {
                return ResourceManager.GetString("form_status_wait_client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 等待客户端结束... 的本地化字符串。
        /// </summary>
        internal static string form_status_wait_close {
            get {
                return ResourceManager.GetString("form_status_wait_close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上传日志到 Pastebin 的本地化字符串。
        /// </summary>
        internal static string form_upload_log {
            get {
                return ResourceManager.GetString("form_upload_log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 匹配系统 的本地化字符串。
        /// </summary>
        internal static string match_windows {
            get {
                return ResourceManager.GetString("match_windows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过时的翻译文件，现在将开始强制修改。 的本地化字符串。
        /// </summary>
        internal static string notice_outdated_translation {
            get {
                return ResourceManager.GetString("notice_outdated_translation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 某些更改仅会在重新启动应用程序后应用。 的本地化字符串。
        /// </summary>
        internal static string notice_pending_restart {
            get {
                return ResourceManager.GetString("notice_pending_restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 双击以还原... 的本地化字符串。
        /// </summary>
        internal static string notify_balloon_text {
            get {
                return ResourceManager.GetString("notify_balloon_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改器隐藏了 的本地化字符串。
        /// </summary>
        internal static string notify_balloon_title {
            get {
                return ResourceManager.GetString("notify_balloon_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Soulworker Patcher 的本地化字符串。
        /// </summary>
        internal static string notify_text {
            get {
                return ResourceManager.GetString("notify_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This program comes with ABSOLUTELY NO WARRANTY
        ///This is free software, and you are welcome to redistribute it under certain conditions.
        ///
        ///Soulworker Patcher 可以轻松地将最新翻译修改到 Soulworker 客户端，而不会在更新时损坏原始文件。
        ///它还可以从SWHQ翻译团队下载最新的翻译，并随时应用。 的本地化字符串。
        /// </summary>
        internal static string patcher_description {
            get {
                return ResourceManager.GetString("patcher_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发现备份文件。您想现在将它们恢复到客户端中吗？
        ///来自客户端的现有版本将被替换为 {0} 翻译版本。
        ///选择“否”将删除这些备份文件。 的本地化字符串。
        /// </summary>
        internal static string question_backup_files_found {
            get {
                return ResourceManager.GetString("question_backup_files_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改器位于游戏同一文件夹或子文件夹下。
        ///这可能使游戏客户端故障或造成数据冲突。
        ///您确定要设置到这个文件夹吗？ 的本地化字符串。
        /// </summary>
        internal static string question_folder_same_path_game {
            get {
                return ResourceManager.GetString("question_folder_same_path_game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日志上传到了 &quot;{0}&quot;
        ///链接已复制到剪切板。 的本地化字符串。
        /// </summary>
        internal static string success_log_file_upload {
            get {
                return ResourceManager.GetString("success_log_file_upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 凭证 的本地化字符串。
        /// </summary>
        internal static string tab_credentials {
            get {
                return ResourceManager.GetString("tab_credentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Soulworker 的本地化字符串。
        /// </summary>
        internal static string tab_game {
            get {
                return ResourceManager.GetString("tab_game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改器 的本地化字符串。
        /// </summary>
        internal static string tab_patcher {
            get {
                return ResourceManager.GetString("tab_patcher", resourceCulture);
            }
        }
    }
}
